/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const AnimatePresence: typeof import('motion/react').AnimatePresence
  const Fragment: typeof import('react').Fragment
  const Suspense: typeof import('react').Suspense
  const createPortal: typeof import('react-dom').createPortal
  const motion: typeof import('motion/react').motion
  const useCallback: typeof import('react').useCallback
  const useEffect: typeof import('react').useEffect
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLocation: typeof import('react-router').useLocation
  const useMemo: typeof import('react').useMemo
  const useNavigate: typeof import('react-router').useNavigate
  const useParams: typeof import('react-router').useParams
  const useRef: typeof import('react').useRef
  const useRoutes: typeof import('react-router').useRoutes
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ReactNode, ComponentProps } from 'react'
  import('react')
}
